### ISSUE TITLE
Come up with a game idea

### ISSUE THREAD

**Issue by rhroberts** [rhroberts/ludumdare49#1]
# Theme: Unstable

## Word Association

**Physically unstable**

Unbalanced, wobbly, unsteady, rickety, precarious, teetering...

**Mentally unstable**

Deranged, unhinged, insane, crazed, disturbed, neurotic...
    Unstable relationships
    - Dating game??

**Chemically unstable**
Alchemy

**Comment by dmarc3** [comment]
## Hiking / Climbing / Mountaineering Game 
Concept is hiking up a mountain to the very peak. Have potential to incorporate unstable in several ways:
- Unstable terrain -> scree, bouldering, chasm bridges, mud, snow, ice, etc.
- Weather impacts -> wind, rain, snow, etc.
- Extreme event -> earthquake, avalanche?
- Unstable climbing partner -> altitude sickness -> starts attacking you?
- Center of gravity management w/ equipment?
- Climb Everest, Rainier, Adams, K2, Kilimanjaro or some large peak

Sidescroller/platformer with changing terrain w/ altitude. Could go into separate view for any climbing portions?

**Comment by dmarc3** [comment]
### Upside Down Platformer
Concept is a regular platformer where an event would occur (randomly or prescribed) where gravity would change and the background would rotate such that the ceiling is now the ground and vice versa. "Physics of the world are unstable".
- Could build a sci-fi / cyberpunk type platformer with story to describe why the anomaly is occurring
- Would complicate map design since we would have to build both ceilings and ground to be playable (Tiled / Asperite intensive)
- Could add effect where when rotation occurs, your allies are now your enemies and your enemies are now your allies. "Alternate universe".

**Comment by dmarc3** [comment]
### Fantasy Alchemist RogueLIFE :mage: :drop_of_blood: :bed: :stethoscope:
Concept is a roguelite where you are an alchemist in a fantasy world attending to a handful of patients. Each play through you will attempt to heal N number of patients. Each patient will have a specific ailment which the player must determine based off of conversation with each patient. The player will have an alchemy lab with a set of ingredients to make potions. Each ingredient will have some flavor text so that the player may deduce the result of mixing certain ingredients. Administering the player created potion may have.... unstable results :frog: 💥
- Total number of patients => Number of available ailments  > Patients to treat each run through
- Each play through would have random ailments applied to randomly selected patients
- Would have to develop matrix of ingredient effects
- Envisioning a top down pokemon-esque style
- Would be heavily text / creativity / music / art driven -> little to no physics necessary outside basic collisions for navigating map

**Comment by dmarc3** [comment]
> 
> ### Fantasy Alchemist RogueLIFE 🧙 🩸 🛏️ 🩺
> 
> Concept is a roguelite where you are an alchemist in a fantasy world attending to a handful of patients. Each play through you will attempt to heal a set number of patients. Each patient will have a specific ailment which the player must determine based off of conversation with each patient. The player will have an alchemy lab with a set of ingredients to make potions. Each ingredient will have some flavor text so that the player may deduce the result of mixing certain ingredients. Administering the player created potion may have.... unstable results! 🐸 💥 The goal would be to save all patients in a single play through which would more than likely require playing a bunch of times to learn what side effects are tied to what illnesses and what ingredients treat what symptoms.
> 
>     * Total number of patients => Number of available ailments  > Patients to treat each run through
> 
>     * Each play through would have random ailments applied to randomly selected patients
> 
>     * Would have to develop matrix of ingredient effects
> 
>     * Envisioning a top down pokemon-esque style
> 
>     * Would be heavily text / creativity / music / art driven -> little to no physics necessary outside basic collisions for navigating map

**Comment by halfhorst** [comment]
## Unstable Relationships

Herding animals into a pen. Sheep? you have a herding dog or two, but they don't listen so good. Maybe you can do things to influence their behavior, but you can't control them directly. Get all the sheep into the pen

**Comment by rhroberts** [comment]
and the winner is.... Full Medical Alchemist!
